### PR TITLE
List virtual monitors with controls in a sidebar

### LINKED ISSUE #74: Put displays in sidebar
A while back @Philip-Scott and I did a round of redesigns to fix some problems with the display settings. One thing we settled on was putting the displays into a sidebar on the left. This primarily lets us remove disabled displays from the layout.

img_20171212_170739

### LINKED ISSUE #131: "Use this Display" switch doesn't work
I just installed Juno and I noticed that disabling my ThinkPad X230's internal display doesn't work. It just stays on.

Steps to reproduce:
Boot into Juno install media or install it and then:
1. Connect an external monitor to your laptop
2. System Settings -> Display
3. Flip the "Use this Display" switch on your internal display
4. Apply the changes
5. See how nothing has changed at all

### LINKED ISSUE #274: Can't disable displays using the "Use this display" toggle
## What Happened

I tried to disable one of my two monitors, and after applying the change, both displays are still active and the Wingpanel is very confused about where to go:

screenshot-2020-11-27-18:02:31

## Expected Behavior

The disabled display no longer receives a signal.

## Steps to Reproduce

1. Use a two-monitor setup (in my case, a laptop plus an external monitor using USB-C)
2. Open the "Displays" widget and disable one of the displays
3. Observe how both displays are still active

## Platform Information

Elementary OS 5.1.7
Lenovo ThinkPad T15p with a 4K screen and an external 1440p Dell monitor via USB-C.

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #74
Fixes #131 
Fixes #274 

Moves monitor controls into a sidebar, more in line with other plugs. Display view mainly used for positioning. 

 - [x] Add sidebar
 - [x] Add monitor widgets with use switch
 - [x] Connect use switch and apply effects
 - [x] Refresh sidebar and view when configuration changes

Some effort went into making sure the plug is stable when reversing proposed changes and cancelling changes after application.  Some of these issues may have been present in master and may now be fixed:

#294 
#292? 
#289 
#287(part2)
#273 
#269?
#226 
#128 

So far it has only been tested with one external and one builtin monitor.

### CODE REVIEW

**Comment by cassidyjames** [comment]
@jeremypw I haven't built this locally yet, but I suppose this fixes #74 as well? :wink:

**Comment by cassidyjames** [comment]
@jeremypw Okay I pulled this to look at it. I think this might actually be too disruptive design-wise; in #74 I kept the "Configure display" gear menu at the top-right of each display, and only used the sidebar to enable/disable displays. I think I like that more as generally configuring displays should not be necessary; the defaults are good, but enabling/disabling and rearranging is the primary use.

**Comment by jeremypw** [comment]
DisplaySidebar
DisplaySidebarInactive

**Comment by jeremypw** [comment]
I did put screenshots in originally - but forgot to press Enter!
I wasn't aware of #74 tbh.
In an early version of this I put the display configuration controls under a MenuButton in each Sidebar widget, but since there is plenty of space in the sidebar, there didn't seem a lot of point in hiding them.  Personally I think it is more logical to have all the controls together in the sidebar and just use the display view to show and adjust the layout of the the displays.  The plug (like most plugs) is not going to be used regularly anyway.

**Comment by jeremypw** [comment]
I would not be averse to putting the controls into a revealer so that they are not always visible though.

**Comment by cassidyjames** [comment]
@jeremypw It doesn't really make sense with the typical design of a sidebar, though, and would require a whole new design to try and decide how it would work. I would really like to keep the controls as they are in master in a popover on the layout widgets as I originally designed.

**Comment by jeremypw** [comment]
OK, will revert the controls (except the active switch) to the display widget.

**Comment by jeremypw** [comment]
Now looks like this.

SwitchboardDisplayPlugSidebar

**Comment by jeremypw** [comment]
COnverting to draft as does not fully implement the linked design issue.

**Comment by mustafa-git** [comment]
#131 and #274 have been broken since Juno if not earlier and preventing me (and possibly others) from using Elementary. Rather than going unfixed for another release, could the developers perhaps merge the fixes and discuss design separately? Sorry if it's any inconvenience.

**Comment by jeremypw** [comment]
Tbh, I had forgotten about this PR. Not sure what needs to be done with it now.  I guess I can try and pull out the fixes and apply to the existing UI.

**Pull request closed without merging**
