### PR TITLE
No inactive display widget

### LINKED ISSUE #131: "Use this Display" switch doesn't work
I just installed Juno and I noticed that disabling my ThinkPad X230's internal display doesn't work. It just stays on.

Steps to reproduce:
Boot into Juno install media or install it and then:
1. Connect an external monitor to your laptop
2. System Settings -> Display
3. Flip the "Use this Display" switch on your internal display
4. Apply the changes
5. See how nothing has changed at all

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #131 

Based on the PR by @shavitmichael (#197), extending it by showing inactive monitors as a button not as a displaywidget in order to solve layout problems.  

Only tested on two monitors without mirroring so far.  Small issue with colors of display widgets changing when deactivating and reactivating one but I think that can be fixed in a separate PR if necessary as there is no simple fix that I can see.

### CODE REVIEW

**Comment by jeremypw** [comment]
Appearance after disabling one monitor:
Screenshot from 2020-02-28 15 46 39

**Comment by jeremypw** [comment]
Clicking on the button shows:
Screenshot from 2020-02-28 15 50 00
Screenshot from 2020-02-28 15 46 39

**Comment by jeremypw** [comment]
Clicking "Apply" shows:
Screenshot from 2020-02-28 15 52 02

**Comment by jeremypw** [comment]
Note that the reactivated monitor is always added on the right of the existing monitors by default (disabled monitors always return 0,0 as their origin) but could be moved before pressing "Apply".  Ability to remember the original position in settings or otherwise could be added in another PR.

**Comment by jeremypw** [comment]
There are some weird layout problems with three monitors (internal, HDMI, VGA) need to check how much of this is in master.

**Comment by jeremypw** [comment]
Seems to work OK with three monitors now.

**Comment by MarlonMrN** [comment]
@danrabbit Hello Daniel, any updates reviewing this PR? It's a really annoying thing thats affecting everyone with multiple monitors on Hera. 


@jeremypw 
   Is there any way to apply this fix by hand? This PR is taking so long to get approved....
   Also, do you have any idea how long this would take to actually get available for ppl to use?
   One last thing, if dan don't approve it in the near future. is there a way to request another reviewer?

**Comment by jeremypw** [comment]
@MarlonMrN To try out this PR you need to have git installed. You can then clone this repo and checkout this branch. You can then build and install it as per the README.md.

Further information, if needed, on building stuff for elementary can be found here: `https://elementary.io/docs/code/getting-started#getting-started`

I requested a review from one of the UX team because a significant change to the appearance is involved. You used to be able to request a review from the UX team as a whole but due to changes in Github you now have to specify a person.  But anyone in the UX team can review.

**Comment by cassidyjames** [comment]
Hmm, this seems to be an improvement (it makes the switch work and seems to make the layout work better, but I have a few issues:

- I'm not sure it's going to be obvious to users that they need to click the little collapsed display to re-enable it. This might come down to its location and visual styling.
- I still seem to have issues re-enabling displays after they're disabled, without first changing some other settings. I ended up with only an external display enabled and everything too-big (HiDPI somehow turned on), which would have been very difficult for most users to recover from.

Considering it is going from not working to working (but with issues), I'm not sure if we want to merge and file follow-up issues, or try and resolve them here first.

**Review by cassidyjames — DISMISSED** [review]
See previous comment.

**Comment by jeremypw** [comment]
@cassidyjames  Thanks for the review. I imagine we want a more complex widget to represent an inactivated display, perhaps with a label and a "Re-enable" button?  I'll do some more debugging to try and iron out the issues you found.

**Comment by EllenJou** [comment]
Users that doesn't use the integrated gpu display at all, should disable it in BIOS.

**Comment by jeremypw** [comment]
@cassidyjames I have added some more text and a tooltip to the inactive display button - is this enough for this PR? The design could be iterated later.

**Comment by jeremypw** [comment]
If you could identify the exact conditions under which you experienced problems reactivating a display I'll try to fix, but I have not experienced problems using two LoDPI displays.

**Comment by jeremypw** [comment]
Note: This PR still compiles on Hera so could be released.

**Comment by cassidyjames** [comment]
@jeremypw I am still able to reproduce the issue above. I disabled my built-in (HiDPI) display, and then am unable to re-enable it; the UI shows it as enabled but it doesn't turn on. Once I change the scaling factor, the built-in display turn back on and I can recover.

But still, this is working better than master, so I'm inclined to merge and iterate.

**Comment by jeremypw** [comment]
I do not have an HiDPI display so it would be better if another developer worked on that aspect.

**Comment by jeremypw** [comment]
This needs someone with a HiDPI display to complete.

**Comment by jeremypw** [comment]
Closing in favour of #298

**Pull request closed without merging**
