### PR TITLE
Fix use this display switch

### LINKED ISSUE #131: "Use this Display" switch doesn't work
I just installed Juno and I noticed that disabling my ThinkPad X230's internal display doesn't work. It just stays on.

Steps to reproduce:
Boot into Juno install media or install it and then:
1. Connect an external monitor to your laptop
2. System Settings -> Display
3. Flip the "Use this Display" switch on your internal display
4. Apply the changes
5. See how nothing has changed at all

### PR DESCRIPTION
**Pull request by davidmhewitt**
Fixes #131 

There have been a few attempts at solving this issue, most of which seem to revolve around redesigning large parts of the plug and then they never get much traction as a result.

This fixes the linked issue in the most minimally invasive way possible.

### CODE REVIEW

**Comment by cassidyjames** [comment]
@davidmhewitt thank you for this! I think the only remaining thing is to change the primary display as well, as if the disabled display is set as primary, the switch appears to do nothing (but changing the primary and _then_ disabling the display works). Alternatively, we can disable the switch on the primary display.

**Review by cassidyjames — APPROVED** [review]
This improves over the behavior in main; I'll file any nits as a follow-up.

**Comment by Hedronmx** [comment]
Not sure if I should post this or open a new issue but I compiled the master and the switch still does nothing, even when changing primary display.

I get `** (io.elementary.switchboard:7219): CRITICAL **: 15:30:33.253: MonitorManager.vala:241: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Logical monitors positions are offset`


Screenshot from 2021-08-18 15-31-01

**Comment by davidmhewitt** [comment]
You should open a new issue. It would be hard to keep track of issues reported in merged pull requests.

In your new issue, could you explain the physical layout of your monitors and where in the logical layout the monitor you tried to disable was? It looks like it's on top in your screenshot, but I'm not sure if that's a side effect of trying to disable it.

**Comment by Hedronmx** [comment]
@davidmhewitt Just made a new issue, thanks for your time.

**Pull request merged**
