### PR TITLE
Port to GTK4

### PR DESCRIPTION
**Pull request by danirabbit**
#379 will solve some new warnings that come in GTK 4 but it's not strictly necessary to merge it first

### CODE REVIEW

**Review by jeremypw — CHANGES_REQUESTED** [review]
All the layout/syntax changes look good.

However the display widget popover does not close when the "Apply" button is pressed or the background clicked - only when "Esc" is pressed.  Then pressing "Apply" applies the changes.  This differs from the behaviour of `master`.

There is also a layout issue when one of the displays is rotated, which is not present in `master`, the settings menu button is misplaced:

Screenshot from 2024-02-26 13 08 03

**Comment by danirabbit** [comment]
@jeremypw fixed the button placement issue, but I also noticed since in GTK 4 the button is actually a child widget of MenuButton and MenuButton isn't a button subclass that it breaks some of the CSS here. This should be fixed with #379 so I'll leave that up to you if you think that should be merged first.

It looks like the popover's autohide gets broken when the displaywidget changes, so I have it popdown now when one of these breaking changes would occur. Is that an okay solution? I'm not sure how to solve it otherwise

**Comment by jeremypw** [comment]
@danirabbit Could you resolve the conflicts please?

**Comment by danirabbit** [comment]
@jeremypw done!

**Review by jeremypw — APPROVED** [review]
Everything looks good now. Trying to mirror two displays causes a crash but is not associated with changes made here so I'll raise an issue.

**Pull request merged**
