### PR TITLE
Use Mutter API to do DPI changes

### PR DESCRIPTION
**Pull request by davidmhewitt**
Potentially supersedes #145 

Couple of things to note:

- I've removed the "Automatic" option as there doesn't seem to be a good way to apply/calculate it through the mutter API. The "preferred" scale on my single HiDPI monitor is `1`. So that's not great.
- I can't find a good signal to connect to that'll allow to combo to react to external changes. Even clicking revert on the "Do you want to keep these settings?" dialog doesn't update the combo.

So, any input into those things would be appreciated.

### CODE REVIEW

**Comment by danrabbit** [comment]
This is probably the right way to do things and it's nice that it applies immediately. I agree that this supersedes #145 and we can close that.

I'm fairly certain that setting a scaling factor of `0` should be the automatic setting for Mutter. Is this not the case?

Since these settings apply immediately, we can remove the infobar that informs the user they need to restart to apply changes right?

**Comment by davidmhewitt** [comment]
A scaling factor of `0` in mutter is invalid and you just get an error in the console.

I'll look at removing the infobar soon

**Comment by danrabbit** [comment]
Maybe @tintou, @donadigo, or @ricotz have more insight, but I would be inclined to say "Perfect is the enemy of good" and this branch makes master better than the current state :shipit:

**Comment by tintou** [comment]
When dealing with the Mutter API there is no automagic value, so we have to compute the best fit ourselves if we want to have an "automatic" value

**Comment by donadigo** [comment]
Yes, there is no "default" value in Mutter API for this. Does anybody know if it is possible to get the value through some kind of heuristic? Otherwise, I'm fine with this if this is an improvement over master.

**Comment by davidmhewitt** [comment]
In the first comment, I noted that the `preferred_scale` on all modes for my 13" 3200x1800 display comes back as `1`. So, using the lowest compatible scale, the automatic option would select `1` as the scaling factor.

This monitor is unusable without a magnifying glass with a scaling factor of `1`, so the automatic option should definitely pick `2` for it.

I think it's more likely that we'd want to look for whatever algorithm the automatic scaling in GSD or whatever sets it usually uses and replicate it. But I think that's a bit outside the scope of this as I was just trying to do a quick PR to get this dropdown to do *something* again.

**Comment by cassidyjames** [comment]
GSD uses/used a DPI of 192. I have a bit more interesting of an approach at github.com/cassidyjames/dippi

**Comment by cassidyjames** [comment]
(but yes, a working but non-perfect combo is better than a completely broken one, so I'm :+1: even in its current state)

**Pull request merged**
