### PR TITLE
Display.css: Improve look with dark style

### LINKED ISSUE #259: Colors really bright in dark style
Screenshot from 2020-09-08 18 38 11@2x

And those borders aren't very crisp

### PR DESCRIPTION
**Pull request by cassidyjames**
This makes the display color slightly transparent which lowers the contrast with the background a bit. The result is darker displays with dark style, and slightly lighter displays with the light style. While I was here, I also updated the CSS style to better match what we're doing elsewhere, including:

- Explicit `white` instead of `#fff`
- No spaces in GtkCSS functions

I left the white active state for the active display for now; it looks no worse than before, but I feel like there is probably something better to do. Targeting `.colored.background` for the on-screen identifier also feels a bit… weird. Input welcome.

## This branch

Light | Dark
---|---
Screenshot from 2020-10-26 12 30 18 | Screenshot from 2020-10-26 12 29 08

## master

Light | Dark
---|---
Screenshot from 2020-10-26 12 30 10 | Screenshot from 2020-10-26 12 29 17

Intended to fix #259

### CODE REVIEW

**Comment by danrabbit** [comment]
So I was thinking about this the other day and I wonder if this is another case where we could be using `@selected_bg_color`

**Comment by cassidyjames** [comment]
@danrabbit u so smart

**Comment by jeremypw** [comment]
@cassidyjames This PR seems to have stalled but has support - any change of finishing it?

**Comment by cassidyjames** [comment]
@jeremypw I haven't actually thought through how to change it to use the stylesheet variables @danrabbit mentioned; I think it might require more of a refactor than I was attempting originally. I'd be fine either merging this as-is for now since it's at least an improvement, or pursuing the other way when someone has the time to do so.

**Comment by jeremypw** [comment]
@danrabbit I do not know enough about stylesheets to help with this - can you?  Or is it worth merging as is and improving later?

**Review by jeremypw — APPROVED** [review]
Tones down the brightness of the display widgets in dark mode.  Any improvements can be  done in a future PR if required.

**Pull request merged**
