### PR TITLE
Deprioritize unrecommended resolutions

### LINKED ISSUE #178: Be smarter about resolutions shown
Right now, we show every. single. resolution. reported as supported by the display

Screenshot from 2019-08-23 14 56 43@2x

This is whack. Instead, we should filter these by default with a way to expose all supported resolutions. At the very least, we should hide or deprioritize too-low resolutions that aren't supported by elementary OS in the first place. On HiDPI, we could also make sure the native resolution and the pixel-halved resolution (if supported) is shown—i.e. 3840×2160 and 1920×1080.

### LINKED ISSUE #252: Mark resolution combo as insensitive if only one resolution
Like we do for refresh rates. PINEBOOK Pro, for example, only has 1920×1080 as a supported resolution.

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #178 
Fixes #252 

The resolution combobox is replaced by a MenuButton/Popover built from a MenuModel.  This allows less recommended resolutions to be put in a submenu.  The main menu just shows resolutions with native aspect ratio and width >= 1024 px.

If this design is accepted, then the other two comboboxes can be replaced by a similar design for consistency either in this PR on in further PRs.

### CODE REVIEW

**Comment by jeremypw** [comment]
ResolutionMenuClosed
ResolutionMenuRecommended
ResolutionMenuOther

**Comment by jeremypw** [comment]
@cassidyjames As this is in response to one of your PRs, I would welcome your comments.

**Comment by jeremypw** [comment]
Should resolutions with widths less than 1024px not be offered at all or put in a further submenu?

**Comment by cassidyjames** [comment]
@jeremypw 

- [ ] I think to start it would make sense to drop the aspect ratio from the main list (since they're all always going to match the native ratio).

- [ ] It could make sense to drop any too-low resolutions in with the “Other…” resolutions as they are all non-ideal in one way or another. And then it make sense to list all aspect ratios in this submenu since they’re likely to differ.

**Comment by jeremypw** [comment]
Now also fixes issue #252

**Comment by cassidyjames** [comment]
@jeremypw I'm happy with the organization of the data now, I think I just want to think about the UI. A popover in a popover is a bit awkward, and I don't think we've used this sort of pattern with a label and then a dropdown button with a popover next to it. Might be worth getting a second opinion from @elementary/ux—or I could take a stab at iterating on the whole popover. :grimacing:

**Comment by jeremypw** [comment]
@cassidyjames I admit I am not too happy with the way Gtk.Popover implements submenus but that is an upstream issue. I wanted something that was supported in Gtk4.  If we move away from using a submenu then there are other possibilities e.g. having a "Show all" switch which repopulates the list.

**Comment by jeremypw** [comment]
Is there anywhere else in elementary system that has the current value displayed with a list of alternative shown with a click which *doesn't* use a combobox? In most cases the number of alternatives is small so a combobox is suitable. But you cannot put a submenu in a combobox afaik.

We may have to build a custom widget to put in popover rather than using its native menu facility.  I'll work on it.

**Comment by jeremypw** [comment]
Another case where there are a large number of alternatives in a combobox is when choosing a locale - in that case the list is so long that it gets put in a scrolled window the height of the screen - which is not ideal.

**Comment by jeremypw** [comment]
Applying flat styleclass to the menubutton
ResolutionListFlatButton (1)

After rejecting too small resolution, the "Other" list is more manageable
ResolutionListRejecing

**Comment by jeremypw** [comment]
I've just realized that the combobox list does not have to be flat - it can have a tree structure. So it should be possible to hide the non-recommended resolutions in a "sub-folder" by preparing the underlying treemodel appropriately.  I'll prepare an alternative PR on this basis.

**Comment by jeremypw** [comment]
Closing in favour of #302

**Pull request closed without merging**
