### PR TITLE
Prefer the resolution modes marked is_preferred

### LINKED ISSUE #338: Resolution reported incorrectly
### What Happened?

[I think the LG UltraGear 32GP850-B has a quirk in its EDID - it reports its max supported resolution as 3840 * 2160 resolution despite it actually being a 2560 * 1440 panel]

On other OSes, they normally come up in 4k with this monitor doing a shoddy job of downscaling. Elementary OS 7 seems to get it right, coming up in 2560 * 1440, however the Display Settings screen reports it as 3840 * 2160 at 60Hz.

If I switch to the 2k resolution, nothing happens to the screen but I get the is it ok prompt. Then I can switch to 4k at 60 Hz properly this time, the screen goes black and comes back in all its tiny downscaled glory. Once I'm there, I can successfully switch back to 2560 * 1440 at 144Hz (screen shot of settings attached). 

Screenshot from 2023-02-01 16 47 40

However, when I close and reopen display settings, the screen is showing that my monitor is running at 3840 * 2160 at 60Hz again.

Screenshot from 2023-02-01 16 48 41

### Steps to Reproduce

Open display settings

### Expected Behavior

The resolution and refresh rate should be correct

### OS Version

Elementary OS 7.0 (Horus)

### Software Version

Latest release with all current updates

### Log Output

No response

### Hardware Info:
Monitor: LG UltraGear 32GP850-B
CPU: i5-10210U
iGPU: UHD 620

### PR DESCRIPTION
**Pull request by vjr**
Fixes #338 

This patch checks whether the `is_preferred` flag has been set on any of the modes and if so then only add those modes to the recommended resolution list and the rest to the other list.

If none of the modes have the `is_preferred` flag set to true then the current behaviour is maintained.

Current behaviour (before this patch) is that the max supported resolutions aspect ratio (not necessarily native) are placed into the recommended list with undesirable (?) results, at least on my 4K UHD (3840x2160) TV with native aspect ratio of 16:9

See the before and after screenshots:

BEFORE:

display_before_cropped

AFTER:

display_after_cropped

### CODE REVIEW

**Comment by vjr** [comment]
Second commit pushed to restore the recommended list because the first commit was hiding all the other non-preferred native resolutions on my main monitor.

Now the TV resolution list (acceptable?) looks like this:

display_after2_cropped

**Comment by vjr** [comment]
Fixes #338 

Going ahead and marking it ready for review because I was able to repro the issue and resolve with this PR.

If anyone from @elementary/desktop-developers can also test, at least that existing functionality works for you?

**Comment by zeebok** [comment]
Code itself looks alright. I can test this either later tonight or tomorrow for you!

**Comment by vjr** [comment]
The person who reported the issue has commented there that this PR resolves it for them too.

Note that there's still some improvements that can be done for re populating the resolution combobox when clicking APPLY or navigate away from the plug and returning back for which I have a diff in progress that I can propose after this PR gets merged.

**Review by tintou — APPROVED** [review]
Nice work!

**Pull request merged**
