### PR TITLE
Reimplement resolution combobox as tree

### LINKED ISSUE #178: Be smarter about resolutions shown
Right now, we show every. single. resolution. reported as supported by the display

Screenshot from 2019-08-23 14 56 43@2x

This is whack. Instead, we should filter these by default with a way to expose all supported resolutions. At the very least, we should hide or deprioritize too-low resolutions that aren't supported by elementary OS in the first place. On HiDPI, we could also make sure the native resolution and the pixel-halved resolution (if supported) is shown—i.e. 3840×2160 and 1920×1080.

### LINKED ISSUE #252: Mark resolution combo as insensitive if only one resolution
Like we do for refresh rates. PINEBOOK Pro, for example, only has 1920×1080 as a supported resolution.

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #178
Fixes #252 

A simpler alternative to #301 keeping the existing combobox and using a TreeStore as model.

### CODE REVIEW

**Comment by cassidyjames** [comment]
I like this a lot more! It seems like a smaller change UX-wise and is really straightforward. I have eventual design changes in the back of my mind that I can work through in a new issue, but I'm happy with this as-is for now.

**Comment by jeremypw** [comment]
Yes, I was so used to comboboxes having flat lists that I didn't consider using a TreeStore with them :disappointed: .  They still feel a bit "old technology" and using TreeStores and TreeIters is a bit fiddly but this is a much smaller diff. I'll withdraw the other PR and ask for a code review on this one.

**Comment by cassidyjames** [comment]
@jeremypw I found a weird quirk: [due to a weird default resolution, I've added an additional (higher) resolution with `xrandr`](https://community.frame.work/t/using-elementary-os-on-the-framework-laptop/4453). This shows up at the bottom of the list instead of the top, and when opening the popover, it is not selected even when it's actually active. I can reproduce this reliably when closing and re-opening the plug in the PR, but not in master (it's still at the bottom of the list in master, but is correctly selected when active).

**Review by cassidyjames — APPROVED** [review]
I've been using this for a while now and am happy with it. Nice work @jeremypw!

**Pull request merged**
